name: Build Docker Images (API/Orchestrator & Sim Worker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the API Gateway/Orchestrator image
      run: docker compose -p bowling build api-orchestrator
    - name: Save API Gateway/Orchestrator image to tarball
      run: docker save -o api-orchestrator-image.tar bowling-api-orchestrator
    - name: Build the Simulation Worker image
      run: docker compose -p bowling build sim-worker
    - name: Save Simulation Worker image to tarball
      run: docker save -o sim-worker-image.tar bowling-sim-worker
    - name: Trivy Scan (API Gateway/Orchestrator)
      uses: aquasecurity/trivy-action@0.34.1
      with:
        input: api-orchestrator-image.tar
        severity: 'CRITICAL,HIGH'
    - name: Trivy Scan (Simulation Worker)
      uses: aquasecurity/trivy-action@0.34.1
      with:
        input: sim-worker-image.tar
        severity: 'CRITICAL,HIGH'
      
